/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asmbms;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static jdk.nashorn.internal.objects.Global.getDate;

/**
 *
 * @author AL AMIN
 */
public class createAccount extends javax.swing.JFrame {

    /**
     * Creates new form createAccount
     */
    public createAccount() {
        initComponents();
    }
    String gender,am ;
    String s,s1,value1,val;
    int a,b,sum,rev,sum1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nameOfAccount = new javax.swing.JTextField();
        accountNumber = new javax.swing.JTextField();
        nameOfNominee = new javax.swing.JTextField();
        fatherName = new javax.swing.JTextField();
        motherName = new javax.swing.JTextField();
        spouseName = new javax.swing.JTextField();
        pVillage = new javax.swing.JTextField();
        pThana = new javax.swing.JTextField();
        pDistrict = new javax.swing.JTextField();
        pCode = new javax.swing.JTextField();
        DOB = new org.jdesktop.swingx.JXDatePicker();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        accountType = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        village = new javax.swing.JTextField();
        thana = new javax.swing.JTextField();
        district = new javax.swing.JTextField();
        postCode = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobileNumber = new javax.swing.JTextField();
        nationalty = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        date = new org.jdesktop.swingx.JXDatePicker();
        SAVED = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Details Of  Account : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Name of Account : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Account of Number : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("Account Type : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Name of Nominee : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Father's Name : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Mother's Name : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("Spouse Name : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setText("Date of Birth : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("Gender : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Present Address : ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel12.setText("Name of Village : ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel13.setText("Name of Upazila/Thana : ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setText("Name of District : ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel15.setText("Post Code : ");

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        male.setText("Male");

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        female.setText("Female");

        accountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Savings Account", "Current Account", "Recurring Deposit Account", "Fixed Deposit Account", " " }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setText("Permanent Address : ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel17.setText("Name of Village : ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel18.setText("Name of Upazila/Thana : ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel19.setText("Name of District : ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel20.setText("Post Code : ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel21.setText("Occupation : ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel22.setText("ID/Smart Card No : ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel23.setText("Date  : ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel24.setText("Email : ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel25.setText("Mobile Number : ");

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel26.setText("Nationalty : ");

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel27.setText("Amount : ");

        SAVED.setText("Saved");
        SAVED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEDActionPerformed(evt);
            }
        });

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Back");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 153));
        jLabel28.setText("Search Account Number : ");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(female))
                            .addComponent(accountNumber)
                            .addComponent(nameOfNominee)
                            .addComponent(motherName)
                            .addComponent(spouseName)
                            .addComponent(pVillage)
                            .addComponent(pThana)
                            .addComponent(pDistrict)
                            .addComponent(pCode)
                            .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameOfAccount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(141, 141, 141)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel25))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nationalty, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mobileNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(occupation, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(postCode, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(district, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thana, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(village, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton)
                                .addGap(31, 31, 31)
                                .addComponent(clearButton)
                                .addGap(18, 18, 18)
                                .addComponent(SAVED)))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(village, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(thana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(district, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(postCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(mobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(nationalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deleteButton)
                                .addComponent(searchButton)
                                .addComponent(update))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SAVED)
                                .addComponent(clearButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameOfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nameOfNominee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(motherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(spouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(male)
                            .addComponent(female))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pVillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pThana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SAVEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEDActionPerformed
        // TODO add your handling code here:
        //Saved Button :
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=asmBank;integratedSecurity=true;";
            Connection con = DriverManager.getConnection(url);
            String sql = "insert  into detailsOfNominee1(nameOfAccount,accountNumber,accountType,nameOfNominee,nameOfFathers,nameOfMothers,nameOfSpouse,dateOfBirth,gender,pnameOfvillage,pnameOfThana,pnameOfDistrict,ppostCode,nameOfvillage,nameOfThana,nameOfDistrict,postCode,occuption,idOfNumber,startingDate,email,mobileNo,nationalty,amount)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, nameOfAccount.getText());
            pst.setString(2, accountNumber.getText());
            // i=room.getSelectedItem().toString();
            //String type;
            //type=accountType.getSelectedItem().toString();
            pst.setString(3, (String)accountType.getSelectedItem());
            
            pst.setString(4, nameOfNominee.getText());
            pst.setString(5, fatherName.getText());
            pst.setString(6, motherName.getText());
            pst.setString(7, spouseName.getText());
            //d=dob.getDate().toString();
            pst.setString(8, DOB.getDate().toString());
            
            
            
            if(male.isSelected()){
                gender="Male";
            }
            if(female.isSelected()){
                gender="Female";
            }
            pst.setString(9, gender);
            
            pst.setString(10, pVillage.getText());
            pst.setString(11, pThana.getText());
            pst.setString(12, pDistrict.getText());
            pst.setString(13, pCode.getText());
            
            pst.setString(14, village.getText());
            pst.setString(15, thana.getText());
            pst.setString(16, district.getText());
            pst.setString(17, postCode.getText());
            pst.setString(18, occupation.getText());
            pst.setString(19, ID.getText());
            pst.setString(20, date.getDate().toString());
            
            pst.setString(21, email.getText());
            pst.setString(22, mobileNumber.getText());
            pst.setString(23, nationalty.getText());
            
            
            //am=amount.getText();
            //int a=Integer.parseInt(am);
            //pst.setString(24, a);
            pst.setString(24, amount.getText());
            pst.executeUpdate();
            
            
            
            
            JOptionPane.showMessageDialog(null,"Insert successfull");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_SAVEDActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        //Clear Button :
        //name.setText("");
        //address.setText("");
        //buttonGroup1.clearSelection();
        //subject.setSelectedIndex(0);
        try{
            
            
             nameOfAccount.setText("");
             accountNumber.setText("");
            //buttonGroup1.clearSelection();

            accountType.setSelectedIndex(0);
            //pst.setString(3, (String)accountType.getSelectedItem());
            
            nameOfNominee.setText("");
            fatherName.setText("");
            motherName.setText("");
            spouseName.setText("");
            
            //checkIn.getEditor().setText("");
             DOB.getEditor().setText("");
            
            buttonGroup1.clearSelection();
            
            
            
            pVillage.setText("");
            pThana.setText("");
            pDistrict.setText("");
            pCode.setText("");
            
            village.setText("");
            thana.setText("");
            district.setText("");
            postCode.setText("");
            occupation.setText("");
            ID.setText("");
            date.getEditor().setText("");//date null
            
            email.setText("");
            mobileNumber.setText("");
            nationalty.setText("");
            
            
       
            amount.setText("");
            searchField.setText("");
            
            
            
            
            
            JOptionPane.showMessageDialog(null," Reset successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        //Back Button :
        try{
            mainPage ob=new mainPage();
            ob.setVisible(true);
            this.setVisible(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        //Delete Button :
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=asmBank;integratedSecurity=true;";
            Connection con = DriverManager.getConnection(url);
            
            String value=searchField.getText();
            String sq1 ="delete from deposit where accountNumber='"+value+"'";
            String sq2 ="delete from transfer1 where accountNumber='"+value+"'";
            String sq3 ="delete from withdraw where accountNumber='"+value+"'";
            String sq4 ="delete from detailsOfNominee1 where accountNumber='"+value+"'";
            PreparedStatement pst1 = con.prepareStatement(sq1); 
            PreparedStatement pst2 = con.prepareStatement(sq2); 
            PreparedStatement pst3 = con.prepareStatement(sq3); 
            PreparedStatement pst4 = con.prepareStatement(sq4); 
            pst1.executeUpdate();
            pst2.executeUpdate();
            pst3.executeUpdate();
            pst4.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Deleted successfull");         
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Search button :
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=asmBank;integratedSecurity=true;";
            Connection con = DriverManager.getConnection(url);
            
            String value=searchField.getText();
            String sq ="select * from detailsOfNominee1 where accountNumber='"+value+"'";
            PreparedStatement pst = con.prepareStatement(sq);  
            ResultSet rs=null;
            rs=pst.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Account Number is matched");  
                s=rs.getString("nameOfAccount");
                nameOfAccount.setText(s);
                String acc=rs.getString("accountNumber");
                accountNumber.setText(acc);
                String accType=rs.getString("accountType");
                //accountType.addItem(accType);
                switch(accType){
                        case "Savings Account":
                            accountType.setSelectedIndex(1);
                            break;
                        case "Current Account":
                            accountType.setSelectedIndex(2);
                            break;
                        case "Recurring Deposit Account":
                            accountType.setSelectedIndex(3);
                            break;
                        case "Fixed Deposit Account":
                            accountType.setSelectedIndex(4);
                            break;
                        default :
                            accountType.setSelectedIndex(0);
                            break;
                }
                
                String NNominee=rs.getString("nameOfNominee");
                nameOfNominee.setText(NNominee);
                String fName=rs.getString("nameOfFathers");
                fatherName.setText(fName);
                String mNane=rs.getString("nameOfMothers");
                motherName.setText(mNane);
                String spname=rs.getString("nameOfSpouse");
                spouseName.setText(spname);
                String ob=rs.getString("dateOfBirth");
                //DOB.setDate().toString();
                //((JFormatTextField)DOB.setEditor().getUniComponent()).setText(ob);
                //((JTextField)DOB.setDateEditor("yyyy-mm-dd").getUniComponent()).setText(rs.getString("dateOfBirth"));
                //working gender;
                //Date dt=new simpleDateFormat("yyyy-mm-dd").parse(ob).toSting());
                //simpleDateFormat dt=new simpleDateFormat(ob);
                
                System.out.println(ob);
                //System.out.println(dt);
                //DOB.getDate(dt);
                String mf=rs.getString("gender");
                switch(mf){
                    case "Male":
                        male.setSelected(true);
                        female.setSelected(false);
                        break;
                    case "Female":
                        male.setSelected(false);
                        female.setSelected(true);
                        break;  
                    default :
                        male.setSelected(false);
                        female.setSelected(false);
                        break;
                }
                
                String pVillag=rs.getString("pnameOfvillage");
                pVillage.setText(pVillag);
                String pThan=rs.getString("pnameOfThana");
                pThana.setText(pThan);
                String pDist=rs.getString("pnameOfDistrict");
                pDistrict.setText(pDist);
                String pcode=rs.getString("ppostCode");
                pCode.setText(pcode);
                String vill=rs.getString("nameOfvillage");
                village.setText(vill);
                String than=rs.getString("nameOfThana");
                thana.setText(than);
                String dist=rs.getString("nameOfDistrict");
                district.setText(dist);
                String code=rs.getString("postCode");
                postCode.setText(code);
                String occ=rs.getString("occuption");
                occupation.setText(occ);
                
                String sCard=rs.getString("idOfNumber");
                ID.setText(sCard);
                
                
                //workin date :
                
                
                String eml=rs.getString("email");
                email.setText(eml);
                String phn=rs.getString("mobileNo");
                mobileNumber.setText(phn);
                String nat=rs.getString("nationalty");
                nationalty.setText(nat);
                String amt=rs.getString("amount");
                amount.setText(amt);
           
                //s1=rs.getString("amount");
                //balance1.setText(s1);
                
            }
            
          // JOptionPane.showMessageDialog(null,"Search successfull");         
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
                                           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        // update
        
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=asmBank;integratedSecurity=true;";
            Connection con = DriverManager.getConnection(url);
            
            String value=searchField.getText();
            String sql="update detailsOfNominee1 set nameOfAccount=?,accountType=?,nameOfNominee=?,nameOfFathers=?,nameOfMothers=?,nameOfSpouse=?,dateOfBirth=?,gender=?,pnameOfvillage=?,pnameOfThana=?,pnameOfDistrict=?,ppostCode=?,nameOfvillage=?,nameOfThana=?,nameOfDistrict=?,postCode=?,occuption=?,idOfNumber=?,startingDate=?,email=?,mobileNo=?,nationalty=?,amount=? where accountNumber='"+value+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, nameOfAccount.getText());
            //pst.setString(2, accountNumber.getText());
            // i=room.getSelectedItem().toString();
            //String type;
            //type=accountType.getSelectedItem().toString();
            pst.setString(2, (String)accountType.getSelectedItem());
            
            pst.setString(3, nameOfNominee.getText());
            pst.setString(4, fatherName.getText());
            pst.setString(5, motherName.getText());
            pst.setString(6, spouseName.getText());
            //d=dob.getDate().toString();
            pst.setString(7, DOB.getDate().toString());
            
            
            
            if(male.isSelected()){
                gender="Male";
            }
            if(female.isSelected()){
                gender="Female";
            }
            pst.setString(8, gender);
            
            pst.setString(9, pVillage.getText());
            pst.setString(10, pThana.getText());
            pst.setString(11, pDistrict.getText());
            pst.setString(12, pCode.getText());
            
            pst.setString(13, village.getText());
            pst.setString(14, thana.getText());
            pst.setString(15, district.getText());
            pst.setString(16, postCode.getText());
            pst.setString(17, occupation.getText());
            pst.setString(18, ID.getText());
            pst.setString(19, date.getDate().toString());
            
            pst.setString(20, email.getText());
            pst.setString(21, mobileNumber.getText());
            pst.setString(22, nationalty.getText());
            
            
            //am=amount.getText();
            //int a=Integer.parseInt(am);
            //pst.setString(24, a);
            pst.setString(23, amount.getText());
            pst.executeUpdate();
            
            
            
            
            JOptionPane.showMessageDialog(null,"Update successfull");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        
    }//GEN-LAST:event_updateActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DOB;
    private javax.swing.JTextField ID;
    private javax.swing.JButton SAVED;
    private javax.swing.JTextField accountNumber;
    private javax.swing.JComboBox<String> accountType;
    private javax.swing.JTextField amount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField district;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fatherName;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobileNumber;
    private javax.swing.JTextField motherName;
    private javax.swing.JTextField nameOfAccount;
    private javax.swing.JTextField nameOfNominee;
    private javax.swing.JTextField nationalty;
    private javax.swing.JTextField occupation;
    private javax.swing.JTextField pCode;
    private javax.swing.JTextField pDistrict;
    private javax.swing.JTextField pThana;
    private javax.swing.JTextField pVillage;
    private javax.swing.JTextField postCode;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField spouseName;
    private javax.swing.JTextField thana;
    private javax.swing.JButton update;
    private javax.swing.JTextField village;
    // End of variables declaration//GEN-END:variables
}
