/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asmbms;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author AL AMIN
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
    }
    String s,s1,value1,val,s2,s3,s4;
    int a,b,sum,rev,sum1,a2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        balance1 = new javax.swing.JTextField();
        date1 = new org.jdesktop.swingx.JXDatePicker();
        creditAccount = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        debitBalance = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("TRANSFER : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Search Account Number : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Name of Account : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("Avilable Blalance : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Credit Account Number : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Date : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Total Balance");

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("Amount : ");

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Transfer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount)
                            .addComponent(debitBalance)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(balance1)
                            .addComponent(creditAccount)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(balance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(creditAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(debitBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Search Button :
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=asmBank;integratedSecurity=true;";
            Connection con = DriverManager.getConnection(url);
            
            String value=searchTxt.getText();
            String sq ="select * from detailsOfNominee1 where accountNumber='"+value+"'";
            PreparedStatement pst = con.prepareStatement(sq);  
            ResultSet rs=null;
            rs=pst.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Account Number is matched");  
                s=rs.getString("nameOfAccount");
                name.setText(s);
                s1=rs.getString("amount");
                balance1.setText(s1);
                
            }
            date1.getEditor().setText("");
            creditAccount.setText("");
            amount.setText("");
            debitBalance.setText("");
          // JOptionPane.showMessageDialog(null,"Search successfull");         
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Transfer Button : 
        
        try{
            /*Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=asmBank;integratedSecurity=true;";
            Connection con = DriverManager.getConnection(url);
            String value=searchTxt.getText();
            String sql1="update detailsOfNominee1 set amount=? where accountNumber='"+value+"'";
            PreparedStatement pst1 = con.prepareStatement(sql1);
            
            String sql = "insert  into transfer1(accountNumber,accountName,creditAccountNumber,date1,creditBalance)values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, searchTxt.getText());
            pst.setString(2, name.getText());
            pst.setString(3, creditAccount.getText());
            pst.setString(4, date1.getDate().toString());
            pst.setString(5, amount.getText());*/
            
            
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=asmBank;integratedSecurity=true;";
            Connection con = DriverManager.getConnection(url);
            String value=searchTxt.getText();
            String sql1="update detailsOfNominee1 set amount=? where accountNumber='"+value+"'";
            PreparedStatement pst1 = con.prepareStatement(sql1);
            
            String sql = "insert  into transfer1(accountNumber,accountName,creditAccountNumber,date1,creditBalance)values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, searchTxt.getText());
            pst.setString(2, name.getText());
            pst.setString(3, creditAccount.getText());
            pst.setString(4, date1.getDate().toString());
            pst.setString(5, amount.getText());
            a=Integer.parseInt(s1);
            b=Integer.parseInt(amount.getText());
            sum=a-b;
            
            value1=String.valueOf(sum);
            debitBalance.setText(value1);
            pst1.setString(1, value1);
            pst1.executeUpdate(); 
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Transfer successfull");
            
            String val=creditAccount.getText();
            String sq21 ="select * from detailsOfNominee1 where accountNumber='"+val+"'";
            String sql2="update detailsOfNominee1 set amount=? where accountNumber='"+val+"'";
            PreparedStatement pst2 = con.prepareStatement(sq21);
            PreparedStatement pst3 = con.prepareStatement(sql2);
            
            ResultSet rs2=null;
            rs2=pst2.executeQuery();
            if(rs2.next()){
                //JOptionPane.showMessageDialog(null,"Account Number is matched");  
                s4=rs2.getString("accountNumber");
                s2=rs2.getString("amount");
                
                
            }
            //System.out.println(s4);
            //System.out.println(val);
            if(s4 == null ? val == null : s4.equals(val)){
                a2=Integer.parseInt(s2);
                sum1=a2+b;
                s3=String.valueOf(sum1);
                pst3.setString(1, s3);
                pst3.executeUpdate();
                JOptionPane.showMessageDialog(null,"Transfer successfull Of Same Account Number");
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Not Same Account Number Matching !");
            }
            
            
            
            //JOptionPane.showMessageDialog(null,"Transfer successfull");
            
            
            /*String val=creditAccount.getText();
            String sql2="update detailsOfNominee1 set amount=? where accountNumber='"+val+"'";
            String sq21 ="select * from detailsOfNominee1 where accountNumber='"+val+"'";
            PreparedStatement pst3 = con.prepareStatement(sql2);
            PreparedStatement pst2 = con.prepareStatement(sq21);
            ResultSet rs2=null;
            rs2=pst3.executeQuery();
            if(rs2.next()){
                //JOptionPane.showMessageDialog(null,"Account Number is matched");  
                s4=rs2.getString("nameOfAccount");
                s2=rs2.getString("amount");
                
                
            }
            if(s4.equals(val)){
                a2=Integer.parseInt(s2);
                sum1=a2+b;
                s3=String.valueOf(sum1);
                pst3.setString(2, s3);
                pst2.executeUpdate();
            }*/
            /*a2=Integer.parseInt(s2);
            sum1=a2+b;
            value1=String.valueOf(sum1);
            pst2.setString(1, value1);
            pst2.executeUpdate();*/
            //JOptionPane.showMessageDialog(null,"Transfer successfull");
            con.close();
            
            
            /*String value2=creditAccount.getText();
            String sq12 ="update detailsOfNominee1 set amount=? where accountNumber='"+value2+"'";
            PreparedStatement pst2 = con.prepareStatement(sq12);  
            ResultSet rs=null;
            rs=pst2.executeQuery();            
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Matched Blanked Account!");
                String r=rs.getString("amount");
                rev=Integer.getInteger(r);   
            }
            if(rev!=0){
                a=Integer.parseInt(s1);
                b=Integer.parseInt(amount.getText());
                sum=a-b;
                sum1=rev+b;
                value1=String.valueOf(sum);
                val=String.valueOf(sum1);
                debitBalance.setText(value1);
                //pst2.setString(1, val);
                pst1.setString(1, value1);
                pst2.executeUpdate(); 
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Transfer successfull");
            }
            if(rev!=0){
                JOptionPane.showMessageDialog(null,"Not Matched Blanked Account!");
                a=Integer.parseInt(s1);
                b=Integer.parseInt(amount.getText());
                sum=a-b;
                value1=String.valueOf(sum);
                debitBalance.setText(value1);
                pst1.setString(1, value1);
                pst1.executeUpdate(); 
                
                pst2.executeUpdate(); 
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Transfer successfull");
            }*/
            
            
            /*a=Integer.parseInt(s1);
            b=Integer.parseInt(amount.getText());
            sum=a-b;
            value1=String.valueOf(sum);
            debitBalance.setText(value1);
            pst1.setString(1, value1);
            pst1.executeUpdate(); 
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Transfer successfull");*/
            
           
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Back Button :
        mainPage ob=new mainPage();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //Thread.currentThread().setName("T");
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // Thread.currentThread().setName("T");
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField balance1;
    private javax.swing.JTextField creditAccount;
    private org.jdesktop.swingx.JXDatePicker date1;
    private javax.swing.JTextField debitBalance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
